version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: 
      context: ugc_app/
      dockerfile: Dockerfile.test
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - PYTHON_VERSION="${PYTHON_VERSION}"
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - MONGO_CONNECT=${MONGO_CONNECT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      
  nginx:
    image: nginx:1.19.2
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  mongo_data:
    driver: local
