version: '3.8'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

  web:
    build: ugc_app/
    depends_on:
      - mongodb
    env_file:
      - ugc_app/.env.container
      
  nginx:
    image: nginx:1.19.2
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  mongo_data:
    driver: local
