version: "3.9"
services:
  elasticsearch_data:
    image: elasticsearch:8.12.2
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk

  elasticsearch:
    image: elasticsearch:8.12.2
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
    volumes:
      - elasticsearch-logs:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: kibana:8.12.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  logstash:
    image: logstash:8.10.2
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
      - ./fastapi-solution/fs.log:/opt/app/fs.log:ro
    command: logstash -f /config/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - elk
    environment:
      - LOG_FILE_PATH=/opt/app/fs.log
      - ES_LOGS_HOST=http://elasticsearch:9200

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_vol:/root/redis
    networks:
      - elk

  fastapi-solution:
    build: ./fastapi-solution
    restart: always
    env_file:
      - .env
    ports:
      - "8002:8000"
    depends_on:
      - redis
      - elasticsearch_data
      - logstash
    networks:
      - elk
    volumes:
      - ./fastapi-solution/fs.log:/opt/app/fs.log
      - ./fastapi-solution:/opt/app

volumes:
  elasticsearch-data:
  elasticsearch-logs:
  redis_vol:

networks:
  elk:
    driver: bridge
