version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    deploy:
      resources:
        limits:
          memory: 4GB
    restart: always
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - "9200:9200"

  db_test:
    build: ./test_databases
    container_name: db_test
    depends_on:
      - mongodb
      - elasticsearch

